# BimiTool configuration file.
# Encoding must be set to UTF8.

# Set the currency symbol to be used by the gui.
#currency: '€'

# Set the deposit value. This value will be deducted from the
# balance of each user.
#deposit: 0.0

# Set the number of drink-comboboxes displayed in the GUI.
#num_comboboxes: 4

# Instead of displaying the mail text in the gui, a mail program can
# be launched with the mail data as parameter. Supported programs
# are thunderbird and icedove.
#mail_program: icedove

# Customize the text displayed in the gui-mail-window. The line
# containing $accInfos will be replaced with the names and balances
# of all available accounts.  The part after "$accInfos:" can be
# customized.
#
# $name $balance      -->  M. Bison 13.37€
# $name has $balance! -->  M. Bison has 13.37€!
#
# The line containing $kings will be replaced with those account who
# consumed the most of each drink. Customisation works the same way
# as $accInfos.
summary_mail_subject: Getränkeabrechnung
summary_mail_text: |
    Guten Tag werter Flur,
    die aktuelle Abrechnung der Getränkeliste zeigt folgende Kontostände:

        $accInfos:$name $balance

    des Weiteren präsentiere ich für jede Getränkeklasse die Königinnen und Könige:

        $kings:$drink-King ist $name mit $amount Flaschen

    Auf ein munteres Weiterzechen!
    Euer BiMi

# If credits have been added to an account a mail can be sent to
# confirm the transaction. The mail_program option must be activated
# to use this feature! Two substitution will occur in subject and
# text.
# $amount  --> float value of added credit
# $name    --> account name
credit_mail_subject: Getränkekonto +$amount
credit_mail_text: |
    Hoi $name,
    hiermit ist bestätigt dass $amount auf dein Getränkekonto
    eingezahlt wurde.

    Auf ein munteres Weiterzechen!
    Dein BiMi
